server:
  port: 9999

spring:
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html